---
 - name: Installing Apache Webserver
   become: true
   yum: 
     name: httpd
     state: present

 - name: Installation completed
   debug:
     var: "version"

 - name: Installing mariaDB     
   become: true
   yum:
     name: 
       - mariadb-server
       - MySQL-python 
     state: present

 - name: Restarting mariaDB
   become: true
   service:
        name: mariadb
        state: restarted
        enabled: true

 - name: PHP Installation
   become: true
   yum:
     name: 
       - php
       - php-mysql
